config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'products/index'
  devise_for :users
  root "home#index"
  get "/home", to:  "home#index"
  get "/profile", to:  "profile#index"
  get 'cart', to: "cart#show"

  resources :products
  resources :orders 
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_one :product
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    include ApplicationHelper

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :contact])
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
    @products = Product.all
  end

  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    if @order.save
     redirect_to orders_path
     else
        render 'new'
     end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url notice: 'Order was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  
  private
  def order_params
    params.require(:order).permit(:name)
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show 
    @product = Product.find_by_id(params[:id])
   
  end

  private
  def product_params
    params.require(:product).permit(:name, :image, :price, :details)
  end

  
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/home/index.html.erb
  <main class="lg:relative">
    <div class="mx-auto max-w-7xl w-full pt-16 pb-20 text-center lg:py-48 lg:text-left">
      <div class="px-4 lg:w-1/2 sm:px-8 xl:pr-16">
        <h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl lg:text-7xl xl:text-6xl">
          <span class="block xl:inline">Bean There,</span>
          <span class="block text-green-600 xl:inline">Done that</span>
        </h1>
        <p class="mt-3 max-w-md mx-auto text-lg text-gray-500 sm:text-xl md:mt-5 md:max-w-3xl">Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua.</p>
        <div class="mt-10 sm:flex sm:justify-center lg:justify-start">
          <div class="rounded-md shadow">
            <a href="/products" class="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-green-600 hover: bg-green-500 md:py-4 md:text-lg md:px-10">See all Coffee's</a>
          </div>
          <%if !user_signed_in? %>
          <div class="mt-3 rounded-md shadow sm:mt-0 sm:ml-3">
            <a href="/users/sign_up" class="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-orange-900 bg-white hover:bg-gray-50 md:py-4 md:text-lg md:px-10"> Join Rewards </a>
          </div>
          <%end%>
        </div>
      </div>
    </div>
    <div class="relative w-full h-64 sm:h-72 md:h-96 lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2 lg:h-full">
      <%= image_tag ("coffee/banner"), :class => "h-56 w-full object-cover sm:h-72 md:h-96 lg:w-full lg:h-full" %>
      </div>
  </main>
</div>

<div class="carousel relative container mx-auto" style="max-width:1600px;">
<div class="carousel-inner relative overflow-hidden w-full">
    <!--Slide 1-->
    <input class="carousel-open" type="radio" id="carousel-1" name="carousel" aria-hidden="true" hidden="" checked="checked">
    <div class="carousel-item absolute opacity-0" style="height:50vh;">
        <div class="block h-full w-full mx-auto flex pt-6 md:pt-0 md:items-center bg-cover bg-right" style="background-image: url('https://i.ibb.co/D1mqn0z/imgur.png');">

            <div class="container mx-auto">
                <div class="flex flex-col w-full lg:w-1/2 md:ml-16 items-center md:items-start px-6 tracking-wide">
                    <p class="text-green-900 font bold text-2xl my-4">Coffee 1</p>
                    <a class="text-xl text-black inline-block no-underline border-b border-gray-600 leading-relaxed hover:text-white hover:border-black" href="#">view product</a>
                </div>
            </div>

        </div>
    </div>
    <label for="carousel-3" class="prev control-1 w-10 h-10 ml-2 md:ml-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-gray-900 leading-tight text-center z-10 inset-y-0 left-0 my-auto">‹</label>
    <label for="carousel-2" class="next control-1 w-10 h-10 mr-2 md:mr-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-gray-900 leading-tight text-center z-10 inset-y-0 right-0 my-auto">›</label>

    <!--Slide 2-->
    <input class="carousel-open" type="radio" id="carousel-2" name="carousel" aria-hidden="true" hidden="">
    <div class="carousel-item absolute opacity-0 bg-cover bg-right" style="height:50vh;">
        <div class="block h-full w-full mx-auto flex pt-6 md:pt-0 md:items-center bg-cover bg-right" style="background-image: url('https://i.ibb.co/z4gr3Zt/imgur-1.png');">

            <div class="container mx-auto">
                <div class="flex flex-col w-full lg:w-1/2 md:ml-16 items-center md:items-start px-6 tracking-wide">
                    <p class="text-black text-2xl my-4">Cofee 2</p>
                    <a class="text-xl inline-block no-underline border-b border-gray-600 leading-relaxed hover:text-black hover:border-black" href="#">view product</a>
                </div>
            </div>

        </div>
    </div>
    <label for="carousel-1" class="prev control-2 w-10 h-10 ml-2 md:ml-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-gray-900  leading-tight text-center z-10 inset-y-0 left-0 my-auto">‹</label>
    <label for="carousel-3" class="next control-2 w-10 h-10 mr-2 md:mr-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-gray-900  leading-tight text-center z-10 inset-y-0 right-0 my-auto">›</label>

    <!--Slide 3-->
    <input class="carousel-open" type="radio" id="carousel-3" name="carousel" aria-hidden="true" hidden="">
    <div class="carousel-item absolute opacity-0" style="height:50vh;">
        <div class="block h-full w-full mx-auto flex pt-6 md:pt-0 md:items-center bg-cover bg-bottom" style="background-image: url('https://i.ibb.co/jV3tMTg/imgur-2.png');">

            <div class="container mx-auto">
                <div class="flex flex-col w-full lg:w-1/2 md:ml-16 items-center md:items-start px-6 tracking-wide">
                    <p class="text-white text-2xl my-4">Cofee 3</p>
                    <a class="text-xl inline-block no-underline border-b border-gray-600 leading-relaxed text-white hover:text-black hover:border-black" href="#">view product</a>
                </div>
            </div>

        </div>
    </div>
    <label for="carousel-2" class="prev control-3 w-10 h-10 ml-2 md:ml-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-gray-900  leading-tight text-center z-10 inset-y-0 left-0 my-auto">‹</label>
    <label for="carousel-1" class="next control-3 w-10 h-10 mr-2 md:mr-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-gray-900  leading-tight text-center z-10 inset-y-0 right-0 my-auto">›</label>

    <!-- Add additional indicators for each slide-->
    <ol class="carousel-indicators">
        <li class="inline-block mr-3">
            <label for="carousel-1" class="carousel-bullet cursor-pointer block text-4xl text-gray-400 hover:text-gray-900">•</label>
        </li>
        <li class="inline-block mr-3">
            <label for="carousel-2" class="carousel-bullet cursor-pointer block text-4xl text-gray-400 hover:text-gray-900">•</label>
        </li>
        <li class="inline-block mr-3">
            <label for="carousel-3" class="carousel-bullet cursor-pointer block text-4xl text-gray-400 hover:text-gray-900">•</label>
        </li>
    </ol>

</div>
</div>

<%= render 'layouts/footer' %>

app/views/layouts/_nav.html.erb
<nav id="header" class="w-full z-30 top-0 py-1 bg-green-600">
<div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 px-6 py-3">

  <label for="menu-toggle" class="cursor-pointer md:hidden block">
      <svg class="fill-current text-gray-900" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20">
          <title>menu</title>
          <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
      </svg>
  </label>
  <input class="hidden" type="checkbox" id="menu-toggle" />

  <div class="hidden  md:flex md:items-center md:w-auto w-full order-3 md:order-1" id="menu">
      <nav>
          <ul class="md:flex items-center justify-between text-base text-white pt-4 md:pt-0">
              <li><a class="inline-block font-semibold no-underline text-white hover:text-black  py-2 px-4" href="/products">Our Coffe's</a></li>
          </ul>
      </nav>
  </div>

  <div class="order-1 md:order-2">
      <a class="flex items-center tracking-wide no-underline hover:text-black  font-bold text-white text-xl center mt-2 " href="/home">
      <%= image_tag ("coffee/coffe-bean"),:class=> "flex-shrink-0 h-5 w-5 mb-1 mr-2" %>
          Coffii
      </a>
  </div>

  <div class="order-2 md:order-3 flex items-center" id="nav-content">
  <%if !user_signed_in? %>
      <a class="inline-block no-underline text-white hover:text-black" href="/users/sign_in">
      <%= image_tag ("coffee/user"), :class => "fill-current hover:text-black h-5  w-5" %>

      </a>
      <%else%>
      <a class="inline-block no-underline hover:text-black" href="/profile">

      <%= image_tag ("coffee/user"), :class => "fill-current hover:text-black h-5  w-5" %>

  </a>
     
      <a class="pl-3 inline-block no-underline hover:text-black" href="/orders">
      <%= image_tag ("coffee/shopping-cart"), :class => "fill-current hover:text-black h-5  w-5" %>

      </a>
  
    <%= link_to destroy_user_session_path, :class=>"pl-3 inline-block no-underline hover:text-black", :method => :delete do %>
        <%= image_tag ("coffee/out"), :class => "fill-current hover:text-black h-5  w-5" %>

        <% end %>
<%end%>
  </div>
</div>
</nav>

app/views/orders/index.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Name of Product ordered
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Date ordered
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
             Action
            </th>
            </tr>
          </thead>
          <% @orders.each do |t| %>
          <tbody class="bg-white divide-y divide-gray-200">
            <tr>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
               <%= t.name %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
              <%= t.created_at.asctime %>
              </td>
            
                <td><%= link_to "Delete", order_path(t),
              method: :delete,
              data: { confirm: 'Are you sure you want this to delete?' }, :class=>"text-red-600 ml-5 hover:text-indigo-900 "%></td>
             
            </tr>

            <!-- More people... -->
          </tbody>
          <%end%>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
    <section class="bg-white py-8  bg-gray-200 ">

    <div class="container mx-auto flex items-center flex-wrap pt-4 pb-12">

    
            <% @products.each do |product| %>
    
            <div class="w-full md:w-1/3 xl:w-1/4 p-6 flex flex-col">
        <%if user_signed_in? %>
            <%= link_to product_path(product) do %>
                <%= image_tag product.image.to_s, :class=> "object-cover h-48 w-96 shadow-lg rounded-lg" %> 
            <% end %>

            <%else%>
            <%= link_to new_user_session_path do %>
                <%= image_tag product.image.to_s, :class=> "object-cover h-48 w-96 shadow-lg rounded-lg" %> 
            <% end %>
        <% end %> 
           
                <div class="pt-3 flex items-center justify-between">
                    <%= link_to product.name, product_path(product) %> 
                            <svg class="h-6 w-6 fill-current text-gray-500 hover:text-black" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                <path d="M12,4.595c-1.104-1.006-2.512-1.558-3.996-1.558c-1.578,0-3.072,0.623-4.213,1.758c-2.353,2.363-2.352,6.059,0.002,8.412 l7.332,7.332c0.17,0.299,0.498,0.492,0.875,0.492c0.322,0,0.609-0.163,0.792-0.409l7.415-7.415 c2.354-2.354,2.354-6.049-0.002-8.416c-1.137-1.131-2.631-1.754-4.209-1.754C14.513,3.037,13.104,3.589,12,4.595z M18.791,6.205 c1.563,1.571,1.564,4.025,0.002,5.588L12,18.586l-6.793-6.793C3.645,10.23,3.646,7.776,5.205,6.209 c0.76-0.756,1.754-1.172,2.799-1.172s2.035,0.416,2.789,1.17l0.5,0.5c0.391,0.391,1.023,0.391,1.414,0l0.5-0.5 C14.719,4.698,17.281,4.702,18.791,6.205z" />
                            </svg>
                        </div>
                        <p class="pt-1 text-gray-900"><%= product.price %></p>
                    </div>
                <% end %>
        </div>

</section>



<%= render 'layouts/footer' %>

app/views/products/show.html.erb

<div class="relative z-10" role="dialog" aria-modal="true">
<div class="hidden fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity md:block"></div>

<div class="fixed z-10 inset-0 overflow-y-auto">
  <div class="flex items-stretch md:items-center justify-center min-h-full text-center md:px-2 lg:px-4">
    <div class="flex text-base text-left transform transition w-full md:max-w-2xl md:px-4 md:my-8 lg:max-w-4xl">
      <div class="w-full relative flex items-center bg-white px-4 pt-14 pb-8 overflow-hidden shadow-2xl sm:px-6 sm:pt-8 md:p-6 lg:p-8">
        <button type="button" class="absolute top-4 right-4 text-gray-400 hover:text-gray-500 sm:top-8 sm:right-6 md:top-6 md:right-6 lg:top-8 lg:right-8">
          <span class="sr-only">Close</span>
          <!-- Heroicon name: outline/x -->
          
        </button>
        <%= link_to products_path, :class=>"absolute top-4 right-4 text-gray-400 hover:text-gray-500 sm:top-8 sm:right-6 md:top-6 md:right-6 lg:top-8 lg:right-8" do %>
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
      <% end %>

        <div class="w-full grid grid-cols-1 gap-y-8 gap-x-6 items-start sm:grid-cols-12 lg:gap-x-8">
          <div class="sm:col-span-4 lg:col-span-5">
            <div class="aspect-w-1 aspect-h-1 rounded-lg bg-gray-100 overflow-hidden">
            <%= image_tag @product.image.to_s, :class=> "object-cover h-48 w-96 shadow-lg rounded-lg" %> 
            </div>
          </div>
          <div class="sm:col-span-8 lg:col-span-7">
            <h2 class="text-2xl font-extrabold text-gray-900 sm:pr-12"><%=@product.name%></h2>

            <section aria-labelledby="information-heading" class="mt-3">
              <h3 id="information-heading" class="sr-only">Product information</h3>

              <p class="text-2xl text-gray-900">$<%=@product.price%></p>

              <!-- Reviews -->
              <div class="mt-3">
                <h4 class="sr-only">Reviews</h4>
                <div class="flex items-center">
                  <div class="flex items-center">
                    <!--
                      Heroicon name: solid/star

                      Active: "text-gray-400", Inactive: "text-gray-200"
                    -->
                    <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>

                    <!-- Heroicon name: solid/star -->
                    <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>

                    <!-- Heroicon name: solid/star -->
                    <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>

                    <!-- Heroicon name: solid/star -->
                    <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>

                    <!-- Heroicon name: solid/star -->
                    <svg class="h-5 w-5 flex-shrink-0 text-gray-200" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>
                  </div>
                  <p class="sr-only">3.9 out of 5 stars</p>
                </div>
              </div>

              <div class="mt-6">
                <h4 class="sr-only">Description</h4>
                <p class="text-sm text-gray-700"><%=@product.details%></p>
              </div>
            </section>

            <section aria-labelledby="options-heading" class="mt-6">
              <h3 id="options-heading" class="sr-only">Product options</h3>

              <form>             
                <div class="mt-6">
               <%= link_to "Make order", new_order_path, :class=>"w-full bg-green-600 border border-transparent rounded-md py-3 px-8 flex items-center justify-center text-base font-medium text-white hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-50 focus:ring-indigo-500" %>
                </div>
              </form>

         
            
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>